### ISSUE TITLE
Will this work across 2 Vue instance not in the same hierarchy

### ISSUE THREAD

**Issue by abishekrsrikaanth** [yangmingshan/vue-bus#4]
I have 2 instances of the Vue and have the Event bus initialized on both. I am trying to communicate one vue instance with the other. But this doesn't seem to work.

**Comment by yangmingshan** [comment]
It should work, as long as their constructors are the same. And you don't need instance of the Vue to initialize vue-bus, not sure how you use it. Can you provide a minimum reproducible example?
