### ISSUE TITLE
TypeError when Vue.bus.on (or other methods) is passed somewhere as an argument and only then executed

### ISSUE THREAD

**Issue by nicky1038** [yangmingshan/vue-bus#5]
It's very useful to write the same logic for subscribing/unsubscribing to bus events in a separate function, and then call it passing `Vue.bus.on` or  `Vue.bus.off` as an argument. But for now one cannot do this because of some `this` magic - a `TypeError` occurs.

Here's a minimal example to reproduce this issue:

```
Vue.use(VueBus);

function subscribe() {
	(function(s) {
		s('someevent', () => console.log('handled'));
	})(Vue.bus.on);
}

try {
	subscribe();
} catch(e) {
	alert(`IT'S A BUG! ${e.message}`);
}
```

**Current workaround** is to pass `Vue.bus.on.bind(Vue.bus)` instead of `Vue.bus.on`, but it's definitely not the way it should go.

**Comment by yangmingshan** [comment]
Sorry, I didn't check my inbox in time. I will fix it.

**Comment by yangmingshan** [comment]
It should be good by now.

**Comment by nicky1038** [comment]
I've tried it, now it works perfectly, thank you 👍
